# Setup
title: M3ngL
url: http://m3ngl.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options


# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about

markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true
  link_defs: {}
  auto_links: true